// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:purple_task/core/hive_legacy/hive_entities/category_entity.dart';
import 'package:purple_task/core/hive_legacy/hive_entities/task_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryEntityAdapter());
    registerAdapter(TaskEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryEntityAdapter());
    registerAdapter(TaskEntityAdapter());
  }
}
